### ISSUE TITLE
Reference to elmer on GitHub repo page

### ISSUE THREAD

**Issue by mark-andrews** [tidyverse/ellmer#240]
This issue is not about the source code in repo per se, but about the GitHub's repo webpages. Apologies if I should not be opening an issue for something not related to the source code.

As I understand it, the correct name for the package is now "ellmer" not "elmer", see https://github.com/tidyverse/ellmer/pull/237

In that case, the link to the package website on the GitHub repo's homepage needs to be updated. Here it is as right now:

![Image](https://github.com/user-attachments/assets/3e4dd94b-cfbc-4e19-b50f-c4228eaec1d0)

**Comment by hadley** [comment]
Thanks!
